os:
  - linux
  - osx
language: rust
rust:
  - stable
  - beta
before_script:
  - rustup component add rustfmt clippy
script:
  - set -e # Abort on failure, see https://github.com/travis-ci/travis-ci/issues/1066
  - cargo fmt -- --check
  - cargo build --verbose
  - cargo test --verbose
  - cargo clippy --all-targets --all-features -- -D warnings
matrix:
  include:
    - rust: nightly
      before_script:
        - rustup component add rustfmt
        # Fallback to git in case clippy is not available in the current nightly
        - rustup component add clippy --toolchain=nightly || cargo install --git https://github.com/rust-lang/rust-clippy/ --force clippy
  allow_failures:
    - rust: nightly
