name: nightly
on:
  pull_request:
  push:
    branches:
      - main
      - actions
jobs:
  test:
    name: test
    env:
      # Emit backtraces on panics.
      RUST_BACKTRACE: 1
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build:
          - ubuntu
          - macos
          - win-msvc
        include:
          - build: ubuntu
            os: ubuntu-18.04
            rust: nightly
          - build: macos
            os: macos-latest
            rust: nightly
          - build: win-msvc
            os: windows-2019
            rust: nightly
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          profile: minimal
          override: true

      - name: Build
        run: cargo build --verbose

      # This is useful for debugging problems when the expected build artifacts
      # (like shell completions and man pages) aren't generated.
      - name: Show build.rs stderr
        if: matrix.os == 'windows-2019'
        shell: bash
        run: |
          set +x
          stderr="$(find "./target/debug" -name stderr -print0 | xargs -0 ls -t | head -n1)"
          if [ -s "$stderr" ]; then
            echo "===== $stderr ===== "
            cat "$stderr"
            echo "====="
          fi
          set -x

      - name: Run tests
        run: cargo test --verbose

